version: "2"
## app
services: 
  app:
    build: .
    environment:
      DB_DRIVER: postgre
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
    ports:
      - "80:80"
    volumes:
      - ./assignments:/data/assignments    
    links:
      - postgres:postgres

  ## DB
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
