## app
app:
  #image: liuyang1204/docker-sharif-judge
  build: .
  environment:
    DB_DRIVER: postgre
    DB_HOST: postgres
    DB_USER: postgres
    DB_PASS: postgres
    DB_NAME: postgres
  ports:
    - "80:80"
  volumes:
    - ./assignments:/data/assignments    
  links:
    - postgres:postgres
  #container_name: sharif-judge

## DB
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  #ports:
  #  - "5432:5432"
  #container_name: postgres-db
  volumes_from:
    - postgres-data
  #volumes:
  #  - ./data/postgres:/var/lib/postgresql/data

## data
postgres-data:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
#  container_name: postgres-datastore